FROM golang:alpine

ENV TERRAFORM_VERSION=0.10.0


RUN apk add --update git bash openssh

ENV TF_DEV=true
ENV TF_RELEASE=true
WORKDIR /tf


RUN git clone https://github.com/hashicorp/terraform.git ./ && \

    go mod init terraform && \

    go mod tidy && \

    go mod vendor && \

    git checkout v${TERRAFORM_VERSION} && \

    /bin/bash scripts/build.sh